### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by ey-charles**
Basic user interface for the game:

- Get user input for player names
- Assign each player a different token to identify the moves
- Print a mock board
- Comment on the most important methods for interacting with the game

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments below._

- ### To Highlight
  - [x] It has a descriptive branch name 💯
  - [x] The project follows Git flow. 💯
- ### To Improve
  - [x] [MANDATORY] The `main.rb` doesn't have a UI for these situations.
     - when a player wins.
     - when a player gives an invalid input, and
     - when the game generates a `draw`.
    
  - [ ] [OPTIONAL] In `main.rb` try to improve code readability by using functions.


_Please make all the required changes before you submit another code review. If you have any problem or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by kapkev — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻
### Well done on making the previously required changes, your project is almost done, just a few things before we move on:

- [x] [MANDATORY] The main.rb doesn't have a UI for when the game generates a draw.
- [x] You have a lot of commented code, please remove all of them;

After making the required changes, please submit it again.
<hr>
If you have any question, feel free to reach me through slack

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @ey-charles and @LoxiasCam  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] game tells which player turn it is (without computing who the winner is)
* [x] game asks the player to select from available moves
* [x] game informs player if the selected move is invalid (without computing what an invalid move is)
* [x] game displays board after the player move (without computing which spots on the board are taken)
* [ ] game informs player if the selected move is a winning move (without computing the winning move)
* [ ] In this step milestone, you're supposed to **mock** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`gets.chomp`). The only input your game is collecting right now is the name of both players.
No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won.

##### Implementation details

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside the loop, you should call actions repeated for each move
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by GzimAsani — APPROVED** [review]
# Status: PROJECT APPROVED :+1: : :100:  
## Hello **Team** 👋, good job implementing all the requirements asked from the previous reviewer :muscle:, you have met all the requirements so go ahead and merge this pull request.

_Ps: Don't forget to submit the project completion form_  


### HAPPY CODING :computer:

**Pull request merged**
